In [ ]:
#array -array is collection of similar elemnt


property -1)contigeous
2-similar type element

and python is diffrent type of element store

1-python array module
2- python numpy module

[20,30,40,50,60]
so satrt from 0 to n

array module , numpy

In [2]:
import array
val = array.array('i', [10, 20, 30, 40, 50, 60, 70, 80])
print(val)

array('i', [10, 20, 30, 40, 50, 60, 70, 80])


type code - python data type-byte size
i - int -2
I - int - 2
u - unicode charcter- 2
h - int-2
H -int - 2
L -int - 4
f - flaot -4
d- flaot -8

In [3]:
import array
array.array('i',[1,2,3,4,5,6])
print(val)

array('i', [10, 20, 30, 40, 50, 60, 70, 80])


In [5]:
import array
array.array('i',[1,2,3,4,5,6])

for i in range (0,7): #0 is include and 7 is exclude
  print(val[i])

10
20
30
40
50
60
70


In [6]:
import array
array.array('i',[1,2,3,4,5,6])

for i in range (0,7): #0 is include and 7 is exclude
  print(val[i],end = " ")

10 20 30 40 50 60 70 

In [7]:
for x in val:
  print(x)

10
20
30
40
50
60
70
80


In [8]:
import array as arr

val = arr.array('H',[1,2,3,4,5,6,7,8,9])
print(val[i],end= " ")


7 

In [9]:
from array import*
val = array('i',[1,2,3,4,5,6,7,8,9])

for i in range (0,8):
  print(val[i],end=" ")

1 2 3 4 5 6 7 8 

In [10]:
for i in range(0,len(val)):
  print(val[i],end =" ")

1 2 3 4 5 6 7 8 9 

In [13]:
from array import *
# Type code 'u' requires unicode characters, not integers
val = array('u', ['a', 'b', 'c', 'd', 'e'])

for i in range(0, len(val)):
  print(val[i], end=" ")

a b c d e 

In [14]:
print(val.typecode)

u


In [19]:
from array import*
val = array('i',[1,2,3,4,5,6,7,8,9])

for i in range (0,9):
  print(val[i],end=" ")

print(val.reverse())
for i in range(0,len(val)):
  print(val[i], end=" ")

1 2 3 4 5 6 7 8 9 None
9 8 7 6 5 4 3 2 1 

In [22]:
from array import*
val = array('i',[1,2,3,4,5,6,7,8,9])

for i in range (0,9):
  print(val[i],end=" ")

# insert(index, value) requires two arguments
val.insert(0, 100)

print("\nAfter insertion:")
for i in range(0,len(val)):
  print(val[i], end=" ")

1 2 3 4 5 6 7 8 9 
After insertion:
100 1 2 3 4 5 6 7 8 9 

In [24]:
from array import *
val = array('i',[1,2,3,4,5,6,7,8,9])

for i in range(0,len(val)):
  print(val[i],end=" ")

print("\nAfter insertion:")
val.append(100)
for i in range(0,len(val)):
  print(val[i], end=" ")



1 2 3 4 5 6 7 8 9 
After insertion:
1 2 3 4 5 6 7 8 9 100 

In [27]:
from array import*

val = array('i',[1,2,3,4,5,6,7,8,9])

for i in range(0,len(val)):
  print(val[i],end=",")
print("\nAfter copy:")
copy_array = array(val.typecode,(x**2 for x in val))
for i in range(0,len(val)):
  print(copy_array[i],end=" ")

1,2,3,4,5,6,7,8,9,
After copy:
1 4 9 16 25 36 49 64 81 

In [30]:
from array import*
val = array('i',[1,2,3,4,5,6,7,8])

copy_array = array(val.typecode,(x**2 for x in val))
copy_array.pop(4)

for i in range(0,len(copy_array)):
  print(copy_array[i],end=" ")

1 4 9 16 36 49 64 

In [32]:
copy_array.remove(4)
for i in range (0,len(copy_array)):
    print(copy_array[i],end=" ")

1 9 16 36 49 64 

In [33]:
from array import*
val = array('i',[1,2,3,4,5,6,7,8,9])

a = val[1:5]
for i in range(0,len(a)):
  print(a[i],end= " ")

2 3 4 5 

In [34]:
from array import*
val = array('i',[1,2,3,4,5,6,7,8,9])

a = val[1:-3]
for i in range(0,len(a)):
  print(a[i],end= " ")

2 3 4 5 6 

In [41]:
from array import*

arr = array('i',[])

try:
    line = input("Enter numbers separated by space: ")
    # Split the input string by spaces and convert each part to an integer
    for x in line.split():
        arr.append(int(x))

    print("Array elements:")
    for x in arr:
      print(x, end=" ")
except ValueError:
    print("Invalid input! Please enter only integers separated by spaces.")

Enter numbers separated by space: 
Array elements:


In [42]:
from array import *
arr = array('i',[89,85,98,95,94])

i = arr.index(98)
print(i)

2


#multidimensional array use numpy
if commond prompt use ->       pip install numpy

In [44]:
import numpy as np
# Pass a list of numbers to create a numpy array
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [45]:
from numpy import *
val = array([10, 20, 30, 40, 50])
print(val)
print('\n')
for i in val:
  print(i)

[10 20 30 40 50]


10
20
30
40
50


In [47]:
from numpy import*
val = linspace(10,100,10)

for x in val:
  print(x,end=" ")

10.0 20.0 30.0 40.0 50.0 60.0 70.0 80.0 90.0 100.0 

In [48]:
from numpy import*
val = arange(10,100,10)

for x in val:
  print(x,end=" ")

10 20 30 40 50 60 70 80 90 

In [49]:
from numpy import*
val = full(10,6)

for x in val:
  print(x,end=" ")

6 6 6 6 6 6 6 6 6 6 

In [50]:
from numpy import*

zero = array(10)
print(zero)

10


In [51]:
from numpy import*

one = array([10,20,30,40,50])
print(one)

[10 20 30 40 50]


In [53]:
from numpy import *

two = array([[1,2,3],[4,5,6],[7,8,9]])
print(two)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
from numpy import *

# Creating a valid 3D array (e.g., 2x2x2)
three = array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(three)
print("Shape:", three.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
